# action.yml
name: 'HuaweiCloud CCI Deoloy'
description: 'Action for deploying to Cloud Container Instance(CCI)'
inputs:
  access_key:
    description: "Access key id"
    required: true
  secret_key:
    description: "Secret access key"
    required: true
  region:
    description: 'Region'
    required: true
    default: 'cn-north-4'
  manifest:
    description: "The kubernetes deployment yaml file"
    required: true
  images:
    description: images url(e.g., swr.cn-north-4.myhuaweicloud.com/namespace/demo:v1.1,swr.cn-north-4.myhuaweicloud.com/namespace/demo:v1.2)
    required: true  
branding:
  icon: 'cloud'
  color: 'red'
runs:
  using: 'node16'
  main: 'dist/index.js'

